name: Daily Tech News

on:
  schedule:
    - cron: '0,30 6-20 * * *'    # هر نیم ساعت از ۱۰ صبح تا ۲۳ شب (به وقت UTC)
  workflow_dispatch:

jobs:
  run-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install feedparser requests deep-translator
      
      - name: Run News Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: python news_bot.py
